import { useState } from "react";

const questions = [
  "Do you enjoy parties?",
  "Coffee or tea?",
  "Do you trust your instincts?",
  "Would you rather lead or follow?",
  "Do you like planning trips?",
  "Are you usually early?",
  "Do you enjoy meeting strangers?",
  "What is the 1240th number of pi?",
  "Do you read instructions before using things?",
  "Do you enjoy debates?",
  "Would you rather explore or stay comfortable?",
  "Do you make decisions quickly?",
  "What is your IP address?",
  "If a chicken and a half can lay an egg and a half in a day and a half, how long would it take a  Hummingbird Hawk-moth to lay an egg?",
  "If sand is from rocks are mountains beaches?",
  "Do pizza belong on pineapple?",
  "Do you organise your flies?",
  "If nothing ever sticks to Teflon, how did they get the Teflon to stick to the pan?",
  "What color does a chameleon turn when it is on water?",
  "Are you questioning this test?"
];


const options = [
  "Strongly agree",
  "Agree",
  "Disagree",
  "Strongly disagree"
];


function randomLetters(length){

  const letters="ABCDEFGHIJKLMNOPQRSTUVWXYZ";

  let result="";

  for(let i=0;i<length;i++){

    result+=letters[Math.floor(Math.random()*letters.length)];

  }

  return result;

}


function randomMBTI(){

const types=[
"INTJ","INTP","ENTJ","ENTP",
"INFJ","INFP","ENFJ","ENFP",
"ISTJ","ISFJ","ESTJ","ESFJ",
"ISTP","ISFP","ESTP","ESFP"
];

return types[Math.floor(Math.random()*types.length)];

}



function Navbar({setPage}){

return(

<div className="navbar">

<h3
className="siteTitle"
onClick={()=>setPage("home")}
>
The 2⁴ + 26²⁶ Personality Test
</h3>

</div>

);

}

function Footer(){

return(

<footer>

This website is not affiliated with MBTI, official personality
assessments, or any legitimate psychological testing organisation.
It is a satire project created for entertainment.

</footer>

);

}



function App(){

const saved=localStorage.getItem("result");


const [page,setPage]=useState("home");

const [answers,setAnswers]=useState({});

const [result,setResult]=useState(saved || "");

const [loading,setLoading]=useState(false);



function finishTest(){

setLoading(true);


setTimeout(()=>{

const final=
randomMBTI()+"-"+randomLetters(26);


localStorage.setItem(
"result",
final
);


setResult(final);

setLoading(false);

setPage("result");


},5000);


}



if(loading){

return(

<div className="container">

<Navbar setPage={setPage}/>


<div className="card loading">

<h1>
Computing your personality...
</h1>


<div className="spinner"></div>


<p>
Analysing millions of possibilities
</p>


<h2>
Your personality type is very rare! 
</h2>

<h3>It is 1 in 6 150 958 782 230 893 133 115 890 311 685 563 792 possibilities!</h3>


</div>


<Footer />

</div>

)

}



if(page==="test"){

return(

<div className="container">

<Navbar setPage={setPage}/>


<h1>
The questionable test
</h1>


{
questions.map((q,index)=>(

<div className="card question" key={index}>

<h3>
Q{index+1}. {q}
</h3>


<div className="options">

{
options.map(option=>(

<button

className={
answers[index]===option
?"selected":""
}


onClick={()=>setAnswers({
...answers,
[index]:option
})}

>

{option}

</button>

))

}

</div>


</div>


))

}



<button

disabled={
Object.keys(answers).length!==20
}

className="mainButton"

onClick={finishTest}

>

Reveal my amazing personality

</button>


</div>

)

}




if(page==="result"){

return(

<div className="container">

<Navbar setPage={setPage}/>


<div className="ultimate card">


<p>
Your amazing personality:
</p>


<h1>
You are {result}
</h1>


</div>



<div className="dropdownCard">

<details open>

<summary>
You are {result}
</summary>


<p>

You are a completely unique individual
who possesses the rare combination of
random letters generated by a computer.

</p>

</details>

</div>





<div className="dropdownCard">

<details open>

<summary>
Actually, this is bullshit.
</summary>


<p>

This website is satire. It is satire of so many
websites claiming to test MBTI. Most of such actually 
use other personality frameworks and translate them 
into MBTI, sometimes for profit. People proudly 
proclaim that they are whatever they are without
even understanding what they're talking about. 

</p>

</details>

</div>





<div className="dropdownCard">

<details open>

<summary>
Why?

</summary>


<p>

As of the time of creation, 7 July 2026, the first
test you get when you search "MBTI" is already a false test.
People also tend to accept the answer without truely 
understanding the purpose of MBTI or what anything 
actually means. This ignorance, combined with misinformation
is what I think caused this amazing situation.


</p>

</details>

</div>


<div className="dropdownCard">

<details open>

<summary>
Wait, then how do I figure out my personality?!
</summary>


<p>
Learn it yourself for goodness sake!

Your personality exists already, but these frameworks
can indeed help you understand yourself or self improve. 
If you really want to do the above, why would these bogus websites stop you?


</p>

</details>

</div>


<Footer />
</div>

)

}




return(

<div className="container">


<Navbar setPage={setPage}/>



<header>

<h1>
The 2⁴ + 26²⁶ Personality Test
</h1>


<p className="subtitle">
The best, most amazing personality test ever created.
</p>


<button

className="mainButton"

onClick={()=>setPage("test")}

>

Take our free personality test!

</button>


{
result &&

<div className="card">

<h3>
Your previous personality:
</h3>

<h2>
{result}
</h2>

<button
className="mainButton"
onClick={()=>setPage("result")}
>
View result
</button>


</div>

}



</header>



<div className="dropdownCard">

<details>

<summary>
What is this?
</summary>

<p>
A satire website parodying fake personality quizzes.
</p>

</details>

</div>


<div className="dropdownCard">

<details>

<summary>
Explore all personality possibilites
</summary>

<p>
Joke's on you. 2^4 + 26^26 = 6 150 958 782 230 893 133 115 890 311 685 563 792.
That is too many possibilities, you, assuming the average person, won't even be  able to remember to apply it
and I am too lazy in the first place.
</p>

</details>

</div>


<Footer />



</div>

)

}


export default App;